o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=55) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 2108
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=56) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 4008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=57) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 6008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=58) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 8008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=59) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 10008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=60) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 12006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=61) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 14007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=62) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 16007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=63) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 18007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=64) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 20006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=65) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 22007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=66) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 24006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=67) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 26008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=68) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 28007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=69) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 30007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=70) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 32017
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=71) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 34029
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=72) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 36008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=73) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 38006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=74) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 40007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=75) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 42007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=76) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 44007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=77) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 46007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=78) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 48008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=79) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 50007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=80) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 52008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=81) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 54007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=82) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 56007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=83) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 58007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=84) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 60007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=85) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 62006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=86) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 64007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=87) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 66028
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=88) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 68007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=89) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 70007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=90) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 72007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=91) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 74007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=92) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 76006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=93) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 78007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=94) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 80007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=95) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 82007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=96) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 84007
