o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=29) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 3649
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=30) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 4010
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=31) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 6008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=32) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 8007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=33) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 10007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=34) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 12007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=35) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 14008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=36) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 16007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=37) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 18007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=38) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 20007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=39) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 22007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=40) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 24007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=41) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 26006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=42) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 28006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=43) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 30006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=44) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 32012
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=45) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 34027
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=46) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 36007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=47) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 38006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=48) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 40008
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=49) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 42010
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=50) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 44006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=51) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 46006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=52) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 48007
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=53) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 50006
o.m.jdbc.message.server.ErrorPacket -- Error: 1045-28000: Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
com.mayer.playground.Playground -- PRoblem
java.sql.SQLInvalidAuthorizationSpecException: (conn=54) Access denied for user 'Maximilian'@'172.17.0.1' (using password: NO)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.mayer.playground.Playground.lambda$main$0(Playground.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
com.mayer.playground.Playground -- Scheduled Future called. Time is 52007
